---
title: "Lab 06 - Functions and iterations"
author: "Hannah Teasdale"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}

diamonds2 <- diamonds %>% rename(
    depth = depth_pct,
    x = length_mm,
    y = width_mm,
    z = depth_mm,
    table = table_pct
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

diamonds2 <- diamonds %>%
mutate(clarity_number = case_when(
    clarity == "I1" ~ 1,
    clarity == "SI2" ~ 2,
    clarity == "SI1" ~ 3,
    clarity == "VS2" ~ 4,
    clarity == "VS1" ~ 5,
    clarity == "VVS2" ~ 6,
    clarity == "VVS1" ~ 7,
    clarity == "IF" ~ 8))



```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?

diamonds %>%
summarise(mean(table_mm)) #mean_with_na 

diamonds %>%
summarise(mean(table_mm, rm.na = TRUE)) #mean_without_na



# table_mm arithmetic mean within each clarity category

diamonds2 %>%
group_by(clarity_number, clarity) %>%
summarise(mean(table_mm))



```

As clarity increases, the mean of the table decreases.

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command

gmean <- function(x){
  exp(
    (1/(seq_len(x)))*
  for(i in seq_len(x)){
    log(x) 
  })}

gmean <- function(x){
 (seq_len(x))
  }

y<-c(1,1,1)
(seq_len(y))

gmean(y)
```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples

for(row in test_data){
  mean <- gmean(row)
  print(mean)
}

for(row in test_data){
  mean <- gmean(row)
  print(mean)
}

test_data%>%
gmean(test_data)

```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
